source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.ximalaya.com:iphone/XMSpecs.git'
platform :ios,			'8.0'
#inhibit_all_warnings!

target:'LCSKitDemo'

#pod 'Masonry', '1.1.0'
pod 'MJRefresh','3.5.0', :modular_headers => true
pod 'SnapKit','4.2.0'
pod 'YYCache', '1.0.4', :modular_headers => true
pod 'LCSKit', :path => '../../LCSKit'

#use_modular_headers!

